### ISSUE TITLE
Missing extension method dependency?

### ISSUE THREAD

**Issue by MostHated** [zacx-z/WorkBoard#1]
Hey there,
I wanted to take a look at this, just to see what it looked like, but it seems like it might be missing an extension library or similar?

---
Edit: Ah, I see, preview.Cleanup() must also be part of newer editors > 2020.3. I see that it is/should be a builtin function of the objectpreview.

Throws an error of:

```cs
Packages/com.nelasystem.workboard/Editor/Scripts/PreviewElement.cs(69,47): error CS1061: 
'ObjectPreview' does not contain a definition for 'Cleanup' and no accessible extension method 'Cleanup' accepting a first argument of type 'ObjectPreview' could be found (are you missing a using directive or an assembly reference?)
```
A [quick search](https://github.com/search?q=repo%3Azacx-z%2FWorkBoard%20Cleanup&type=code) of this repo yields no results on that method, so I am guessing it must have been part of another package?

---

There is also an error relating to  `EditorUtility.OpenPropertyEditor()` missing, but I believe that is either only in certain versions, or needs to have the properties package installed, I cannot remember which. I tried to open it in 2020.3, so it might help to have that part #if def'd.

**Comment by zacx-z** [comment]
these compiler errors should be due to editor api changes: this package was created under 2021.3. I'll make it compatible to 2020.3 but some minor features might be unavailable

**Comment by zacx-z** [comment]
fixed in https://github.com/zacx-z/WorkBoard/commit/247140ff5d4fd32fc677a59930439b60212500b2
